version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongo-auth:
    image: mongo:6
    container_name: mongo-auth
    ports:
      - "27017:27017"
    volumes:
      - mongo-auth-data:/data/db

  mongo-product:
    image: mongo:6
    container_name: mongo-product
    ports:
      - "27018:27017"
    volumes:
      - mongo-product-data:/data/db

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    volumes:
      - ./auth-service:/app:cached
      - /app/node_modules
    command: npm run start:dev
    ports:
      - "3001:3000"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo-auth
      - rabbitmq
    restart: unless-stopped

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    volumes:
      - ./product-service:/app:cached
      - /app/node_modules
    command: npm run start:dev
    ports:
      - "3002:3000"
    env_file:
      - ./product-service/.env
    depends_on:
      - mongo-product
      - rabbitmq
    restart: unless-stopped

volumes:
  mongo-auth-data:
  mongo-product-data:
  rabbitmq_data:
